# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9739c3e0120aeab65f0c9903c45f0bfa15497a1169b70bae3b0a39fc5cda793c8a4545b3fbeed2f7f26a2dcb22eb95f178fdb829a335b035c7930b448f173e7b

test:
  secret_key_base: b59e7885341d6b5c5965815c2996c6a2ff4ad2221fa0cac495143610c7aaee6591db8233d55d09716a055ab227762c2029ff0f78566906a39614eebdb7edff3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
